# Dockerfile for building image that contains software stack provisioned by Ansible.
#
# Version  1.1
#

# pull base image
FROM williamyeh/ansible:debian8-onbuild

MAINTAINER Aleksej Gavrilov <le9i0nx@gmail.com>

#
# build phase
#

ENV PLAYBOOK test/test.yml
RUN ls -la
RUN pwd
RUN echo "===> Init test role..."  && \
    mkdir -p /etc/ansible/roles && \
    ln -s /test/group_vars /etc/ansible/group_vars && \
    ln -s /test/host_vars /etc/ansible/host_vars


#
# test phase
#

CMD ["syncthing", "-version"]

